AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for Java Lambda Function

Resources:
  JavaLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: LambdaApplication
      Handler: sportsbet.com.au.lambda.LambdaApplication::handleRequest
      Runtime: java17
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      MemorySize: 512
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

Parameters:
  LambdaCodeS3Bucket:
    Description: S3 bucket where the Lambda code is stored
    Type: String

  LambdaCodeS3Key:
    Description: S3 key of the Lambda code zip file
    Type: String

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda Function
    Value: !GetAtt JavaLambdaFunction.Arn
